CREATE TABLE "USRDBVAH"."TB_LANCA_ARQUIVO"
(
   ID decimal(38,0) PRIMARY KEY NOT NULL,
   ID_ARQU_REMESSA decimal(38,0) NOT NULL,
   TP_ARQUIVO nchar(3),
   DT_ENVIO timestamp,
   DT_RECEBIMENTO decimal(38,0),
   NM_CAMINHO_ARQUIVO nvarchar2(250)
)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_ARQUIVO"
ADD CONSTRAINT ID_ARQUIVO_FK
FOREIGN KEY (ID_ARQU_REMESSA)
REFERENCES "USRDBVAH"."TB_LANCA_ARQUIVO"(ID)
;
CREATE INDEX TB_LANCA_ARQUIVO__IDX ON "USRDBVAH"."TB_LANCA_ARQUIVO"(ID)
;
CREATE TABLE "USRDBVAH"."TB_LANCA_AVALIACAO"
(
   ID decimal(38,0) PRIMARY KEY NOT NULL,
   ID_AVALIACAO_ROOT decimal(38,0) NOT NULL,
   ID_USU_AVALIADOR decimal(38,0) NOT NULL,
   NM_TITULO nvarchar2(250),
   DT_AVALIACAO timestamp,
   SN_STATUS char(1)
)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_AVALIACAO"
ADD CONSTRAINT ID_AVALIACAO_ROOT_FK
FOREIGN KEY (ID_AVALIACAO_ROOT)
REFERENCES "USRDBVAH"."TB_LANCA_AVALIACAO"(ID)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_AVALIACAO"
ADD CONSTRAINT ID_USU_AVALIADOR_FK
FOREIGN KEY (ID_USU_AVALIADOR)
REFERENCES "USRDBVAH"."TB_PTC_USUARIO_PUSER"(ID_PUSER)
;
CREATE INDEX TB_LANCA_AVALIACAO__IDX ON "USRDBVAH"."TB_LANCA_AVALIACAO"(ID)
;
CREATE TABLE "USRDBVAH"."TB_LANCA_BOLETO"
(
   ID decimal(38,0) PRIMARY KEY NOT NULL,
   DT_GERACAO timestamp,
   DT_VENCIMENTO timestamp,
   VL_VALOR decimal(10,2),
   LO_DESCRICAO clob,
   CD_CAMINHO_BOLETO nvarchar2(250)
)
;
CREATE INDEX TB_LANCA_BOLETO__IDX ON "USRDBVAH"."TB_LANCA_BOLETO"(ID)
;
CREATE TABLE "USRDBVAH"."TB_LANCA_CLIENTE"
(
   ID decimal(38,0) PRIMARY KEY NOT NULL,
   NM_TITULO nvarchar2(250),
   CD_FORNECEDOR decimal(38,0)
)
;
CREATE INDEX TB_LANCA_CLIENTE__IDX ON "USRDBVAH"."TB_LANCA_CLIENTE"(ID)
;
CREATE TABLE "USRDBVAH"."TB_LANCA_CLIENTE_SETOR"
(
   ID decimal(38,0) PRIMARY KEY NOT NULL,
   ID_CLIENTE decimal(38,0) NOT NULL,
   ID_SETOR decimal(38,0) NOT NULL
)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_CLIENTE_SETOR"
ADD CONSTRAINT ID_SETOR_FK
FOREIGN KEY (ID_SETOR)
REFERENCES "USRDBVAH"."TB_LANCA_SETOR"(ID)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_CLIENTE_SETOR"
ADD CONSTRAINT ID_CLIENTE_FK
FOREIGN KEY (ID_CLIENTE)
REFERENCES "USRDBVAH"."TB_LANCA_CLIENTE"(ID)
;
CREATE UNIQUE INDEX TB_LANCA_CLIENTE_SETOR_PK ON "USRDBVAH"."TB_LANCA_CLIENTE_SETOR"(ID)
;
CREATE TABLE "USRDBVAH"."TB_LANCA_CONTRATO"
(
   ID decimal(38,0) PRIMARY KEY NOT NULL,
   ID_CLIENTE decimal(38,0) NOT NULL,
   NM_TITULO nvarchar2(250),
   DT_INICIO timestamp,
   DT_FINAL timestamp,
   DT_REAJUSTE timestamp
)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_CONTRATO"
ADD CONSTRAINT ID_CLIENTE_FKV2
FOREIGN KEY (ID_CLIENTE)
REFERENCES "USRDBVAH"."TB_LANCA_CLIENTE"(ID)
;
CREATE INDEX TB_CONTRATO__IDX ON "USRDBVAH"."TB_LANCA_CONTRATO"(ID)
;
CREATE TABLE "USRDBVAH"."TB_LANCA_LANCAMENTO"
(
   ID decimal(38,0) PRIMARY KEY NOT NULL,
   ID_CONTRATO decimal(38,0) NOT NULL,
   ID_SERVICO decimal(38,0) NOT NULL,
   ID_USU_CONTRATO decimal(38,0) NOT NULL,
   ID_USU_LANCADOR decimal(38,0) NOT NULL,
   ID_AVALICAO decimal(38,0) NOT NULL,
   VL_LANCAMENTO decimal(10,2),
   VL_FIXO decimal(10,2),
   VL_VARIAVEL decimal(10,2),
   DT_LANCAMENTO timestamp,
   DT_COMPETENCIA timestamp
)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_LANCAMENTO"
ADD CONSTRAINT ID_AVALIACAO_FK
FOREIGN KEY (ID_AVALICAO)
REFERENCES "USRDBVAH"."TB_LANCA_AVALIACAO"(ID)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_LANCAMENTO"
ADD CONSTRAINT ID_CONTRATO_FK
FOREIGN KEY (ID_CONTRATO)
REFERENCES "USRDBVAH"."TB_LANCA_CONTRATO"(ID)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_LANCAMENTO"
ADD CONSTRAINT ID_USU_CONTRATO_FK
FOREIGN KEY (ID_USU_CONTRATO)
REFERENCES "USRDBVAH"."TB_PTC_USUARIO_PUSER"(ID_PUSER)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_LANCAMENTO"
ADD CONSTRAINT ID_SERVICO_FK
FOREIGN KEY (ID_SERVICO)
REFERENCES "USRDBVAH"."TB_LANCA_SERVICO"(ID)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_LANCAMENTO"
ADD CONSTRAINT ID_USU_LANCADOR_FK
FOREIGN KEY (ID_USU_LANCADOR)
REFERENCES "USRDBVAH"."TB_PTC_USUARIO_PUSER"(ID_PUSER)
;
CREATE INDEX TB_LANCA_LANCAMENTO__IDX ON "USRDBVAH"."TB_LANCA_LANCAMENTO"(ID)
;
CREATE TABLE "USRDBVAH"."TB_LANCA_LANCAMENTO_BOLETO"
(
   ID decimal(38,0) PRIMARY KEY NOT NULL,
   ID_BOLETO decimal(38,0) NOT NULL,
   ID_LANCAMENTO decimal(38,0) NOT NULL
)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_LANCAMENTO_BOLETO"
ADD CONSTRAINT ID_BOLETO_FK
FOREIGN KEY (ID_BOLETO)
REFERENCES "USRDBVAH"."TB_LANCA_BOLETO"(ID)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_LANCAMENTO_BOLETO"
ADD CONSTRAINT ID_LANCAMENTO_FK
FOREIGN KEY (ID_LANCAMENTO)
REFERENCES "USRDBVAH"."TB_LANCA_LANCAMENTO"(ID)
;
CREATE INDEX TB_LNC_LNC_BLT__IDX ON "USRDBVAH"."TB_LANCA_LANCAMENTO_BOLETO"(ID)
;
CREATE TABLE "USRDBVAH"."TB_LANCA_SERVICO"
(
   ID decimal(38,0) PRIMARY KEY NOT NULL,
   ID_TP_SERVICO decimal(38,0) NOT NULL,
   NM_TITULO nvarchar2(250),
   CD_HISTORICO_PADRAO decimal(38,0),
   CD_TP_DOCUMENTO decimal(38,0),
   CD_CONTA_CONTABIL decimal(38,0),
   CD_CONTA_RESULTADO decimal(38,0),
   CD_CONTA_CUSTO decimal(38,0)
)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_SERVICO"
ADD CONSTRAINT ID_TP_SERVICO_FK
FOREIGN KEY (ID_TP_SERVICO)
REFERENCES "USRDBVAH"."TB_LANCA_TIPO_SERVICO"(ID)
;
CREATE INDEX TB_SERVICO__IDX ON "USRDBVAH"."TB_LANCA_SERVICO"(ID)
;
CREATE TABLE "USRDBVAH"."TB_LANCA_SERVICO_CONTRATO"
(
   ID decimal(38,0) PRIMARY KEY NOT NULL,
   ID_SERVICO decimal(38,0) NOT NULL,
   ID_CONTRATO decimal(38,0) NOT NULL,
   VL_SERVICO decimal(10,2)
)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_SERVICO_CONTRATO"
ADD CONSTRAINT ID_SERVICO_FKV2
FOREIGN KEY (ID_SERVICO)
REFERENCES "USRDBVAH"."TB_LANCA_SERVICO"(ID)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_SERVICO_CONTRATO"
ADD CONSTRAINT ID_CONTRATO_FKV2
FOREIGN KEY (ID_CONTRATO)
REFERENCES "USRDBVAH"."TB_LANCA_CONTRATO"(ID)
;
CREATE INDEX TB_LANCA_SERVICO_CONTRATO__IDX ON "USRDBVAH"."TB_LANCA_SERVICO_CONTRATO"(ID)
;
CREATE TABLE "USRDBVAH"."TB_LANCA_SERVICO_USUARIO"
(
   ID decimal(38,0) PRIMARY KEY NOT NULL,
   ID_SERVICO decimal(38,0) NOT NULL,
   ID_USUARIO decimal(38,0) NOT NULL
)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_SERVICO_USUARIO"
ADD CONSTRAINT ID_SERVICO_FKV3
FOREIGN KEY (ID_SERVICO)
REFERENCES "USRDBVAH"."TB_LANCA_SERVICO"(ID)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_SERVICO_USUARIO"
ADD CONSTRAINT ID_USUARIO_FK
FOREIGN KEY (ID_USUARIO)
REFERENCES "USRDBVAH"."TB_LANCA_USUARIO"(ID)
;
CREATE INDEX TB_LANCA_SERVICO_USUARIO__IDX ON "USRDBVAH"."TB_LANCA_SERVICO_USUARIO"(ID)
;
CREATE TABLE "USRDBVAH"."TB_LANCA_SETOR"
(
   ID decimal(38,0) PRIMARY KEY NOT NULL,
   NM_TITULO nvarchar2(250),
   LO_DETALHES clob,
   VL_AREA decimal(10,2)
)
;
CREATE INDEX TB_LANCA_SETOR__IDX ON "USRDBVAH"."TB_LANCA_SETOR"(ID)
;
CREATE TABLE "USRDBVAH"."TB_LANCA_TIPO_SERVICO"
(
   ID decimal(38,0) PRIMARY KEY NOT NULL,
   NM_TITULO nvarchar2(250),
   SN_COBRA_SETOR char(1)
)
;
CREATE UNIQUE INDEX TB_LANCA_TIPO_SERVICO_PK ON "USRDBVAH"."TB_LANCA_TIPO_SERVICO"(ID)
;
CREATE TABLE "USRDBVAH"."TB_LANCA_TRANS_LANC"
(
   ID decimal(38,0) PRIMARY KEY NOT NULL,
   ID_TRANSMISSAO decimal(38,0) NOT NULL,
   ID_LANCAMENTO decimal(38,0) NOT NULL
)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_TRANS_LANC"
ADD CONSTRAINT ID_TRANSMISSAO_FK
FOREIGN KEY (ID_TRANSMISSAO)
REFERENCES "USRDBVAH"."TB_LANCA_TRANSMISSAO"(ID)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_TRANS_LANC"
ADD CONSTRAINT ID_LANCAMENTO_FKV2
FOREIGN KEY (ID_LANCAMENTO)
REFERENCES "USRDBVAH"."TB_LANCA_LANCAMENTO"(ID)
;
CREATE INDEX TB_LANCA_TRANS_LANC__IDX ON "USRDBVAH"."TB_LANCA_TRANS_LANC"(ID)
;
CREATE TABLE "USRDBVAH"."TB_LANCA_TRANSMISSAO"
(
   ID decimal(38,0) PRIMARY KEY NOT NULL,
   ID_ARQUIVO decimal(38,0) NOT NULL,
   DT_TRANSMISSAO timestamp
)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_TRANSMISSAO"
ADD CONSTRAINT ID_ARQUIVO_FKV2
FOREIGN KEY (ID_ARQUIVO)
REFERENCES "USRDBVAH"."TB_LANCA_ARQUIVO"(ID)
;
CREATE INDEX TB_LANCA_TRANSMISSAO__IDX ON "USRDBVAH"."TB_LANCA_TRANSMISSAO"(ID)
;
CREATE TABLE "USRDBVAH"."TB_LANCA_USUARIO"
(
   ID decimal(38,0) PRIMARY KEY NOT NULL,
   ID_USER_PTC decimal(38,0) NOT NULL,
   CD_PERFIL char(1) NOT NULL
)
;
ALTER TABLE "USRDBVAH"."TB_LANCA_USUARIO"
ADD CONSTRAINT ID_USER_PTC_FK
FOREIGN KEY (ID_USER_PTC)
REFERENCES "USRDBVAH"."TB_PTC_USUARIO_PUSER"(ID_PUSER)
;
CREATE INDEX TB_LANCA_USUARIO__IDX ON "USRDBVAH"."TB_LANCA_USUARIO"(ID)
;
CREATE TABLE "USRDBVAH"."TB_PTC_PERFIL_ACESSO"
(
   ID_PERFIL_ACESSO decimal(0,-127) PRIMARY KEY NOT NULL,
   DS_PERFIL_ACESSO nvarchar2(100) NOT NULL
)
;
CREATE UNIQUE INDEX TB_PTC_PERFIL_ACESSO_PK ON "USRDBVAH"."TB_PTC_PERFIL_ACESSO"(ID_PERFIL_ACESSO)
;
CREATE TABLE "USRDBVAH"."TB_PTC_PERFIL_ACESSO_USUARIO"
(
   ID_PUSER decimal(0,-127) NOT NULL,
   ID_PERFIL_ACESSO decimal(0,-127) NOT NULL,
   DATA_CRIACAO timestamp NOT NULL,
   ID_USUARIO_CRIACAO decimal(0,-127) NOT NULL,
   ID_PERFIL_ACESSO_USUARIO decimal(0,-127) PRIMARY KEY NOT NULL
)
;
ALTER TABLE "USRDBVAH"."TB_PTC_PERFIL_ACESSO_USUARIO"
ADD CONSTRAINT PERF_ACESS_USER_ACESS_FK
FOREIGN KEY (ID_PERFIL_ACESSO)
REFERENCES "USRDBVAH"."TB_PTC_PERFIL_ACESSO"(ID_PERFIL_ACESSO)
;
ALTER TABLE "USRDBVAH"."TB_PTC_PERFIL_ACESSO_USUARIO"
ADD CONSTRAINT PERF_ACESS_USER_PUSER_FK
FOREIGN KEY (ID_PUSER)
REFERENCES "USRDBVAH"."TB_PTC_USUARIO_PUSER"(ID_PUSER)
;
CREATE UNIQUE INDEX ID_PERFIL_ACESSO_USUARIO_PK ON "USRDBVAH"."TB_PTC_PERFIL_ACESSO_USUARIO"(ID_PERFIL_ACESSO_USUARIO)
;
CREATE TABLE "USRDBVAH"."TB_PTC_USUARIO_PUSER"
(
   ID_PUSER decimal(0,-127) PRIMARY KEY NOT NULL,
   DS_LOGIN varchar2(50),
   DS_SENHA varchar2(100),
   CD_USUARIO_MV varchar2(50),
   CD_MATRICULA_RM varchar2(6),
   DT_INSERT timestamp DEFAULT current_date
,
   SN_ALTER_SENHA_LOGIN varchar2(1) DEFAULT 'S'
,
   TB_ACESSO varchar2(1) DEFAULT 'U'
,
   DS_EMAIL varchar2(50),
   DS_SENHA_CRIPT varchar2(100),
   ID_ETAPA decimal(0,-127),
   CD_SETOR decimal(0,-127)
)
;
ALTER TABLE "USRDBVAH"."TB_PTC_USUARIO_PUSER"
ADD CONSTRAINT FK_PUSER_ETAPA
FOREIGN KEY (ID_ETAPA)
REFERENCES "USRDBVAH"."TB_PTC_ETAPA_PROCESSO_ETAPA"(ID_ETAPA)
;
CREATE UNIQUE INDEX PK_TB_PTC_USUARIO_PUSER ON "USRDBVAH"."TB_PTC_USUARIO_PUSER"(ID_PUSER)
;
