-- CLIENTE SETOR

CREATE TABLE USRDBVAH.TB_LANCA_CLIENTE_SETOR
(
  CD_FORNECEDOR NUMBER(*),
  CD_SETOR      NUMBER(*),
  CONSTRAINT TB_LANCA_CLIENTE_SETOR_PK PRIMARY KEY (CD_FORNECEDOR, CD_SETOR),
  CONSTRAINT TB_LANCA_CLIENTE_SETOR_FK1 FOREIGN KEY (CD_FORNECEDOR) REFERENCES DBAMV.FORNECEDOR (CD_FORNECEDOR),
  CONSTRAINT TB_LANCA_CLIENTE_SETOR_FK2 FOREIGN KEY (CD_SETOR) REFERENCES DBAMV.TB_SETOR (CD_SETOR)
);

-- LANÇA SERVIÇO

CREATE TABLE USRDBVAH.TB_LANCA_SERVICO
(
  ID                  NUMBER(*) PRIMARY KEY NOT NULL,
  CD_CONTA_CUSTO      NUMBER(*)             NOT NULL,
  CD_HISTORICO_PADRAO NUMBER(*)             NOT NULL,
  CD_TP_DOCUMENTO     NUMBER(*)             NOT NULL,
  CD_CONTA_CONTABIL   NUMBER(*),
  CD_CONTA_RESULTADO  NUMBER(*)             NOT NULL,
  VL_DIA_VENCIMENTO   NUMBER(*),
  VL_DIA_LIMITE       NUMBER(*),
  SN_FATURAVEL        VARCHAR2(1),
  SN_AGRUPAVEL        VARCHAR2(1),
  SN_COMPULSORIO      VARCHAR2(1),
  SN_CONTA_SETOR      VARCHAR2(1),
  NM_TITULO           VARCHAR2(255),
  CD_TIPO             VARCHAR2(255),
  CONSTRAINT TB_LANCA_SERVICO_FK1 FOREIGN KEY (CD_CONTA_CUSTO) REFERENCES DBAMV.ITEM_RES (CD_ITEM_RES),
  CONSTRAINT TB_LANCA_SERVICO_FK2 FOREIGN KEY (CD_HISTORICO_PADRAO) REFERENCES DBAMV.HISTORICO_PADRAO (CD_HISTORICO_PADRAO),
  CONSTRAINT TB_LANCA_SERVICO_FK3 FOREIGN KEY (CD_CONTA_CONTABIL) REFERENCES DBAMV.PLANO_CONTAS (CD_REDUZIDO),
  CONSTRAINT TB_LANCA_SERVICO_FK4 FOREIGN KEY (CD_CONTA_RESULTADO) REFERENCES DBAMV.PLANO_CONTAS (CD_REDUZIDO)
);

CREATE SEQUENCE USRDBVAH.SEQ_LANCA_SERVICO;

-- LANÇA SERVIÇO VALORES

CREATE TABLE USRDBVAH.TB_LANCA_SERVICO_VALORES
(
  ID         NUMBER(*) PRIMARY KEY NOT NULL,
  ID_SERVICO NUMBER(*)             NOT NULL,
  VL_VALOR   NUMBER(16, 6),
  VL_VALOR_A NUMBER(16, 6),
  VL_VALOR_B NUMBER(16, 6),
  VL_VALOR_C NUMBER(16, 6),
  VL_VALOR_D NUMBER(16, 6),
  DT_INICIO  DATE,
  DT_FINAL   DATE,
  CONSTRAINT TB_LANCA_SERV_VALORES_FK1 FOREIGN KEY (ID_SERVICO) REFERENCES USRDBVAH.TB_LANCA_SERVICO (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_LANCA_SERV_VALORES;

-- LANCA USUARIO

CREATE TABLE USRDBVAH.TB_LANCA_USUARIO
(
  ID        NUMBER(*) PRIMARY KEY NOT NULL,
  DS_LOGIN  VARCHAR2(255)         NOT NULL,
  NM_TITULO VARCHAR2(255)
);

CREATE SEQUENCE USRDBVAH.SEQ_LANCA_USUARIO;

-- LANCAMENTO

CREATE TABLE USRDBVAH.TB_LANCA_LANCAMENTO
(
  ID                 NUMBER(*) PRIMARY KEY NOT NULL,
  ID_SERVICO         NUMBER(*)             NOT NULL,
  ID_SERVICO_VALORES NUMBER(*),
  ID_USU_LANCADOR    NUMBER(*)             NOT NULL,
  VL_TOTAL           NUMBER(10, 2),
  VL_AREA_A          NUMBER(10, 2),
  VL_AREA_B          NUMBER(10, 2),
  VL_AREA_C          NUMBER(10, 2),
  VL_MONTANTE        NUMBER(10, 2),
  DT_LANCAMENTO      DATE,
  DT_VIGENCIA        DATE,
  CD_STATUS          VARCHAR2(255)         NOT NULL,
  CONSTRAINT TB_LANCA_LANCAMENTO_FK1 FOREIGN KEY (ID_SERVICO) REFERENCES USRDBVAH.TB_LANCA_SERVICO (ID),
  CONSTRAINT TB_LANCA_LANCAMENTO_FK2 FOREIGN KEY (ID_SERVICO_VALORES) REFERENCES USRDBVAH.TB_LANCA_SERVICO_VALORES (ID),
  CONSTRAINT TB_LANCA_LANCAMENTO_FK3 FOREIGN KEY (ID_USU_LANCADOR) REFERENCES USRDBVAH.TB_LANCA_USUARIO (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_LANCA_LANCAMENTO;

-- COMENTARIOS

CREATE TABLE USRDBVAH.TB_LANCA_COMENTARIOS
(
  ID            NUMBER(*) PRIMARY KEY NOT NULL,
  ID_PUSER      NUMBER(*)             NOT NULL,
  ID_LANCAMENTO NUMBER(*)             NOT NULL,
  DT_CRIACAO    DATE,
  NM_DETALHES   VARCHAR2(255),
  CONSTRAINT TB_LANCA_COMENTARIOS_FK1 FOREIGN KEY (ID_PUSER) REFERENCES USRDBVAH.TB_LANCA_USUARIO (ID),
  CONSTRAINT TB_LANCA_COMENTARIOS_FK2 FOREIGN KEY (ID_LANCAMENTO) REFERENCES USRDBVAH.TB_LANCA_LANCAMENTO (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_LANCA_COMENTARIOS;

-- CONTRATO

CREATE TABLE USRDBVAH.TB_LANCA_CONTRATO
(
  ID                        NUMBER(*) PRIMARY KEY NOT NULL,
  ID_FORNECEDOR_CONTRATANTE NUMBER(*)             NOT NULL,
  DT_INICIO                 DATE,
  DT_REAJUSTE               DATE,
  DT_FINAL                  DATE,
  NM_TITULO                 VARCHAR2(255),
  CONSTRAINT TB_LANCA_CONTRATO_FK1 FOREIGN KEY (ID_FORNECEDOR_CONTRATANTE) REFERENCES DBAMV.FORNECEDOR (CD_FORNECEDOR)
);

CREATE SEQUENCE USRDBVAH.SEQ_LANCA_CONTRATO;

-- CONTRATO SETOR

CREATE TABLE USRDBVAH.TB_LANCA_CONTRATO_SETOR
(
  ID          NUMBER(*) PRIMARY KEY NOT NULL,
  ID_CONTRATO NUMBER(*)             NOT NULL,
  ID_SETOR    NUMBER(*),
  ID_CLIENTE  NUMBER(*),
  CONSTRAINT TB_LANCA_CONTRATO_SETOR_FK1 FOREIGN KEY (ID_CONTRATO) REFERENCES USRDBVAH.TB_LANCA_CONTRATO (ID),
  CONSTRAINT TB_LANCA_CONTRATO_SETOR_FK2 FOREIGN KEY (ID_SETOR) REFERENCES DBAMV.TB_SETOR (CD_SETOR),
  CONSTRAINT TB_LANCA_CONTRATO_SETOR_FK3 FOREIGN KEY (ID_CLIENTE) REFERENCES DBAMV.FORNECEDOR (CD_FORNECEDOR)
);

CREATE SEQUENCE USRDBVAH.SEQ_LANCA_CONTRATO_SETOR;

-- LANCAMENTO VALORES

CREATE TABLE USRDBVAH.TB_LANCA_LANCAMENTO_VALORES
(
  ID                  NUMBER(*) PRIMARY KEY NOT NULL,
  ID_LANCAMENTO       NUMBER(*)             NOT NULL,
  ID_CONTRATO_SERVICO NUMBER(*)             NOT NULL,
  VL_LANCAMENTO       NUMBER(10, 2)         NOT NULL,
  VL_VALOR_A          NUMBER(10, 2),
  VL_VALOR_B          NUMBER(10, 2),
  DT_LANCAMENTO       DATE,
  DT_ATUALIZACAO      DATE,
  CONSTRAINT TB_LANCA_LANC_VAL_FK1 FOREIGN KEY (ID_LANCAMENTO) REFERENCES USRDBVAH.TB_LANCA_LANCAMENTO (ID),
  CONSTRAINT TB_LANCA_LANC_VAL_FK2 FOREIGN KEY (ID_CONTRATO_SERVICO) REFERENCES USRDBVAH.TB_LANCA_CONTRATO_SETOR (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_LANCA_LANC_VALORES;

-- RELACIONAMENTO SERVICO CONTRATO SERVICO

CREATE TABLE USRDBVAH.TB_LANCA_SER_CON_SER
(
  ID         NUMBER(*) NOT NULL,
  ID_SERVICO NUMBER(*) NOT NULL,
  CONSTRAINT TB_LANCA_SER_CON_SER_PK PRIMARY KEY (ID, ID_SERVICO),
  CONSTRAINT TB_LANCA_SER_CON_SER_FK1 FOREIGN KEY (ID) REFERENCES USRDBVAH.TB_LANCA_CONTRATO_SETOR (ID),
  CONSTRAINT TB_LANCA_SER_CON_SER_FK2 FOREIGN KEY (ID_SERVICO) REFERENCES USRDBVAH.TB_LANCA_SERVICO (ID)

);

-- RELACIONAMENTO USUARIO SERVICO

CREATE TABLE USRDBVAH.TB_LANCA_USUARIO_SERVICO
(
  ID_PUSER   NUMBER(*) NOT NULL,
  ID_SERVICO NUMBER(*) NOT NULL,
  CONSTRAINT TB_LANCA_USUARIO_SERVICO_PK PRIMARY KEY (ID_PUSER, ID_SERVICO),
  CONSTRAINT TB_LANCA_USUARIO_SERVICO_FK1 FOREIGN KEY (ID_PUSER) REFERENCES USRDBVAH.TB_LANCA_USUARIO (ID),
  CONSTRAINT TB_LANCA_USUARIO_SERVICO_FK2 FOREIGN KEY (ID_SERVICO) REFERENCES USRDBVAH.TB_LANCA_SERVICO (ID)
);

-- ROLES USUARIOS

CREATE TABLE USRDBVAH.TB_LANCA_USUARIO_ROLE
(
  ID_PUSER NUMBER(*)     NOT NULL,
  CD_ROLE  VARCHAR2(255) NOT NULL,
  CONSTRAINT TB_LANCA_USUARIO_ROLE_PK PRIMARY KEY (ID_PUSER, CD_ROLE)
);

-- DETALHES DE SETOR

CREATE TABLE USRDBVAH.TB_LANCA_SETOR_DETALHE
(
  ID            NUMBER(*) PRIMARY KEY NOT NULL,
  CD_SETOR      NUMBER(*)             NOT NULL,
  CD_REDUZIDO   NUMBER(*),
  VL_AREA_M2    NUMBER(10, 2),
  CD_TIPO       NUMBER(1),
  VL_QTD_TR     NUMBER(8),
  CD_INSC_IMOBI VARCHAR2(50),
  CONSTRAINT TB_LANCA_SETOR_DETALHE_FK1 FOREIGN KEY (CD_SETOR) REFERENCES DBAMV.TB_SETOR (CD_SETOR),
  CONSTRAINT TB_LANCA_SETOR_DETALHE_FK2 FOREIGN KEY (CD_REDUZIDO) REFERENCES DBAMV.PLANO_CONTAS (CD_REDUZIDO)
);

CREATE SEQUENCE USRDBVAH.SEQ_LANCA_SETOR_DETALHE;

-- TABELA DE MEDIDORES

CREATE TABLE USRDBVAH.TB_LANCA_MEDIDOR
(
  ID          NUMBER(*) PRIMARY KEY NOT NULL,
  VL_FATOR    NUMBER(10, 2),
  CD_TIPO     VARCHAR2(3)           NOT NULL,
  NM_CODIGO   VARCHAR2(50)          NOT NULL,
  NM_TITULO   VARCHAR2(50)          NOT NULL,
  NM_DETALHES VARCHAR2(255)
);

CREATE SEQUENCE USRDBVAH.SEQ_LANCA_MEDIDOR;

-- TABELA DE RELAÇÃO ENTRE SETORES E MEDIDORES

CREATE TABLE USRDBVAH.TB_LANCA_SETOR_MEDIDOR
(
  ID            NUMBER(*) PRIMARY KEY NOT NULL,
  CD_SETOR      NUMBER(*)             NOT NULL,
  ID_MEDIDOR    NUMBER(*)             NOT NULL,
  VL_PERCENTUAL NUMBER(16, 6),
  CONSTRAINT TB_LANCA_SETOR_MEDIDOR_FK1 FOREIGN KEY (CD_SETOR) REFERENCES DBAMV.TB_SETOR (CD_SETOR),
  CONSTRAINT TB_LANCA_SETOR_MEDIDOR_FK2 FOREIGN KEY (ID_MEDIDOR) REFERENCES USRDBVAH.TB_LANCA_MEDIDOR (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_LANCA_SETOR_MEDIDOR;

-- TABELA DE RELAÇÃO ENTRE LANÇAMENTOS E MEDIDORES

CREATE TABLE USRDBVAH.TB_LANCA_LEITURAS
(
  ID                  NUMBER(*) PRIMARY KEY NOT NULL,
  ID_LANCAMENTO       NUMBER(*)             NOT NULL,
  ID_MEDIDOR          NUMBER(*)             NOT NULL,
  VL_LEITURA_ATUAL    NUMBER(10, 2),
  VL_LEITURA_ANTERIOR NUMBER(10, 2),
  CONSTRAINT TB_LANCA_LEITURAS_FK1 FOREIGN KEY (ID_LANCAMENTO) REFERENCES USRDBVAH.TB_LANCA_LANCAMENTO (ID),
  CONSTRAINT TB_LANCA_LEITURAS_FK2 FOREIGN KEY (ID_MEDIDOR) REFERENCES USRDBVAH.TB_LANCA_MEDIDOR (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_LANCA_LEITURAS;

--  RELACIONAMENTO LANCAMENTO CONTA A RECEBER

CREATE TABLE USRDBVAH.TB_LANCA_LAN_CON_REC
(
  ID         NUMBER(*),
  CD_CON_REC NUMBER(*),
  CONSTRAINT TB_LANCA_LAN_CON_REC_PK PRIMARY KEY (ID, CD_CON_REC),
  CONSTRAINT FK_LANCA_LAN_CON_REC_FK1 FOREIGN KEY (ID) REFERENCES USRDBVAH.TB_LANCA_LANCAMENTO (ID),
  CONSTRAINT FK_LANCA_LAN_CON_REC_FK2 FOREIGN KEY (CD_CON_REC) REFERENCES DBAMV.CON_REC (CD_CON_REC)
);

-- TABELA TB_LANCA_CON_SER

CREATE TABLE USRDBVAH.TB_LANCA_CON_SER
(
  ID_CONTRATO NUMBER(*),
  ID_SERVICO  NUMBER(*),
  CONSTRAINT TB_LANCA_CON_SER_PK PRIMARY KEY (ID_CONTRATO, ID_SERVICO),
  CONSTRAINT FK_LANCA_CON_SER_FK1 FOREIGN KEY (ID_CONTRATO) REFERENCES USRDBVAH.TB_LANCA_CONTRATO (ID),
  CONSTRAINT FK_LANCA_CON_SER_FK2 FOREIGN KEY (ID_SERVICO) REFERENCES USRDBVAH.TB_LANCA_SERVICO (ID)
);

-- TABELA TB_LANCA_ARQUIVO

CREATE TABLE USRDBVAH.TB_LANCA_ARQUIVO
(
  ID       NUMBER(*) PRIMARY KEY NOT NULL,
  ID_AUTOR NUMBER(*)             NOT NULL,
  CONSTRAINT TB_LANCA_ARQUIVO_FK1 FOREIGN KEY (ID_AUTOR) REFERENCES USRDBVAH.TB_LANCA_USUARIO (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_LANCA_ARQUIVO;

-- TABELA TB_LANCA_COBRANCA

CREATE TABLE USRDBVAH.TB_LANCA_COBRANCA
(
  ID            NUMBER(*) PRIMARY KEY NOT NULL,
  ID_CLIENTE    NUMBER(*)             NOT NULL,
  ID_ARQUIVO    NUMBER(*)             NOT NULL,
  ID_SETOR      NUMBER(*),
  VL_VALOR      NUMBER(10, 2),
  DT_VIGENCIA   DATE                  NOT NULL,
  DT_VENCIMENTO DATE                  NOT NULL,
  SN_LIQUIDADO  VARCHAR2(1)           NOT NULL,
  SN_BAIXA_MV   VARCHAR2(1)           NOT NULL,
  NM_DOCUMENTO  VARCHAR2(10)          NOT NULL,
  CONSTRAINT TB_LANCA_COBRANCA_FK1 FOREIGN KEY (ID_CLIENTE) REFERENCES DBAMV.FORNECEDOR (CD_FORNECEDOR),
  CONSTRAINT TB_LANCA_COBRANCA_FK2 FOREIGN KEY (ID_ARQUIVO) REFERENCES USRDBVAH.TB_LANCA_ARQUIVO (ID),
  CONSTRAINT TB_LANCA_COBRANCA_FK3 FOREIGN KEY (ID_SETOR) REFERENCES DBAMV.TB_SETOR (CD_SETOR)
);

CREATE SEQUENCE USRDBVAH.SEQ_LANCA_COBRANCA;

-- TABELA TB_LANCA_ITEM_COBRANCA

CREATE TABLE USRDBVAH.TB_LANCA_ITEM_COBRANCA
(
  ID          NUMBER(*) PRIMARY KEY NOT NULL,
  ID_SERVICO  NUMBER(*)             NOT NULL,
  ID_COBRANCA NUMBER(*)             NOT NULL,
  VL_VALOR    NUMBER(10, 2)         NOT NULL,
  VL_TOTAL    NUMBER(10, 2)         NOT NULL,
  CONSTRAINT TB_LANCA_ITEM_CONTRATO_FK1 FOREIGN KEY (ID_SERVICO) REFERENCES USRDBVAH.TB_LANCA_SERVICO (ID),
  CONSTRAINT TB_LANCA_ITEM_COBRANCA_FK2 FOREIGN KEY (ID_COBRANCA) REFERENCES USRDBVAH.TB_LANCA_COBRANCA (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_LANCA_ITEM_COBRANCA;

-- TABELA TB_LANCA_COBRANCA_CONTA

CREATE TABLE USRDBVAH.TB_LANCA_COBRANCA_CONTA
(
  ID_COBRANCA NUMBER(*) NOT NULL,
  CD_SETOR NUMBER(*) NOT NULL,
  CONSTRAINT TB_LANCA_COBRANCA_CONTA_PK PRIMARY KEY (ID_COBRANCA, CD_SETOR),
  CONSTRAINT TB_LANCA_COBRANCA_CONTA_FK1 FOREIGN KEY (ID_COBRANCA) REFERENCES USRDBVAH.TB_LANCA_COBRANCA (ID)
);