INSERT INTO TB_PTC_USUARIO_PUSER VALUES(1, 'admin', 'admin');
INSERT INTO TB_PTC_USUARIO_PUSER VALUES(2, 'user', '123');
INSERT INTO TB_PTC_USUARIO_PUSER VALUES(3, 'manager', '123');
INSERT INTO TB_PTC_USUARIO_PUSER VALUES(4, 'supervisor', '123');
INSERT INTO TB_PTC_USUARIO_PUSER VALUES(5, 'accountant', '123');
