INSERT INTO TB_PTC_USUARIO_PUSER VALUES(1, 'admin', 'admin');
INSERT INTO TB_PTC_USUARIO_PUSER VALUES(2, 'user', '1234');
INSERT INTO TB_PTC_USUARIO_PUSER VALUES(3, 'manager', '123');
INSERT INTO TB_PTC_USUARIO_PUSER VALUES(4, 'supervisor', '123');
INSERT INTO TB_PTC_USUARIO_PUSER VALUES(5, 'accountant', '123');

INSERT INTO TB_LANCA_USUARIO_ROLE VALUES(1,'ADMINISTRATOR');
INSERT INTO TB_LANCA_USUARIO_ROLE VALUES(1,'USER');
INSERT INTO TB_LANCA_USUARIO_ROLE VALUES(1,'MANAGER');
INSERT INTO TB_LANCA_USUARIO_ROLE VALUES(1,'SUPERVISOR');
INSERT INTO TB_LANCA_USUARIO_ROLE VALUES(1,'ACCOUNTANT');