package br.com.vah.lance.constant;

/**
 * Created by Jairoportela on 19/09/2016.
 */
public enum OcorrenciasRecebimentoEnum {
  _02("02", "ENTRADA CONFIRMADA COM POSSIBILIDADE DE MENSAGEM (NOTA 20 – TABELA 10)"),
  _03("03", "ENTRADA REJEITADA (NOTA 20 – TABELA 1)"),
  _04("04", "ALTERAÇÃO DE DADOS – NOVA ENTRADA OU ALTERAÇÃO/EXCLUSÃO DE DADOS ACATADA"),
  _05("05", "ALTERAÇÃO DE DADOS – BAIXA"),
  _06("06", "LIQUIDAÇÃO NORMAL"),
  _07("07", "LIQUIDAÇÃO PARCIAL – COBRANÇA INTELIGENTE (B2B)"),
  _08("08", "LIQUIDAÇÃO EM CARTÓRIO"),
  _09("09", "BAIXA SIMPLES"),
  _10("10", "BAIXA POR TER SIDO LIQUIDADO"),
  _11("11", "EM SER (SÓ NO RETORNO MENSAL)"),
  _12("12", "ABATIMENTO CONCEDIDO"),
  _13("13", "ABATIMENTO CANCELADO"),
  _14("14", "VENCIMENTO ALTERADO"),
  _15("15", "BAIXAS REJEITADAS (NOTA 20 – TABELA 4)"),
  _16("16", "INSTRUÇÕES REJEITADAS (NOTA 20 – TABELA 3)"),
  _17("17", "ALTERAÇÃO/EXCLUSÃO DE DADOS REJEITADOS (NOTA 20 – TABELA 2)"),
  _18("18", "COBRANÇA CONTRATUAL – INSTRUÇÕES/ALTERAÇÕES REJEITADAS/PENDENTES (NOTA 20 – TABELA 5)"),
  _19("19", "CONFIRMA RECEBIMENTO DE INSTRUÇÃO DE PROTESTO"),
  _20("20", "CONFIRMA RECEBIMENTO DE INSTRUÇÃO DE SUSTAÇÃO DE PROTESTO /TARIFA"),
  _21("21", "CONFIRMA RECEBIMENTO DE INSTRUÇÃO DE NÃO PROTESTAR"),
  _23("23", "TÍTULO ENVIADO A CARTÓRIO/TARIFA"),
  _24("24", "INSTRUÇÃO DE PROTESTO REJEITADA / SUSTADA / PENDENTE (NOTA 20 – TABELA 7)"),
  _25("25", "ALEGAÇÕES DO PAGADOR (NOTA 20 – TABELA 6)"),
  _26("26", "TARIFA DE AVISO DE COBRANÇA"),
  _27("27", "TARIFA DE EXTRATO POSIÇÃO (B40X)"),
  _28("28", "TARIFA DE RELAÇÃO DAS LIQUIDAÇÕES"),
  _29("29", "TARIFA DE MANUTENÇÃO DE TÍTULOS VENCIDOS"),
  _30("30", "DÉBITO MENSAL DE TARIFAS (PARA ENTRADAS E BAIXAS)"),
  _32("32", "BAIXA POR TER SIDO PROTESTADO"),
  _33("33", "CUSTAS DE PROTESTO"),
  _34("34", "CUSTAS DE SUSTAÇÃO"),
  _35("35", "CUSTAS DE CARTÓRIO DISTRIBUIDOR"),
  _36("36", "CUSTAS DE EDITAL"),
  _37("37", "TARIFA DE EMISSÃO DE BOLETO/TARIFA DE ENVIO DE DUPLICATA"),
  _38("38", "TARIFA DE INSTRUÇÃO"),
  _39("39", "TARIFA DE OCORRÊNCIAS"),
  _40("40", "TARIFA MENSAL DE EMISSÃO DE BOLETO/TARIFA MENSAL DE ENVIO DE DUPLICATA"),
  _41("41", "DÉBITO MENSAL DE TARIFAS – EXTRATO DE POSIÇÃO (B4EP/B4OX)"),
  _42("42", "DÉBITO MENSAL DE TARIFAS – OUTRAS INSTRUÇÕES"),
  _43("43", "DÉBITO MENSAL DE TARIFAS – MANUTENÇÃO DE TÍTULOS VENCIDOS"),
  _44("44", "DÉBITO MENSAL DE TARIFAS – OUTRAS OCORRÊNCIAS"),
  _45("45", "DÉBITO MENSAL DE TARIFAS – PROTESTO"),
  _46("46", "DÉBITO MENSAL DE TARIFAS – SUSTAÇÃO DE PROTESTO"),
  _47("47", "BAIXA COM TRANSFERÊNCIA PARA DESCONTO"),
  _48("48", "CUSTAS DE SUSTAÇÃO JUDICIAL"),
  _51("51", "TARIFA MENSAL REF A ENTRADAS BANCOS CORRESPONDENTES NA CARTEIRA"),
  _52("52", "TARIFA MENSAL BAIXAS NA CARTEIRA"),
  _53("53", "TARIFA MENSAL BAIXAS EM BANCOS CORRESPONDENTES NA CARTEIRA"),
  _54("54", "TARIFA MENSAL DE LIQUIDAÇÕES NA CARTEIRA"),
  _55("55", "TARIFA MENSAL DE LIQUIDAÇÕES EM BANCOS CORRESPONDENTES NA CARTEIRA"),
  _56("56", "CUSTAS DE IRREGULARIDADE"),
  _57("57", "INSTRUÇÃO CANCELADA (NOTA 20 – TABELA 8)"),
  _59("59", "BAIXA POR CRÉDITO EM C/C ATRAVÉS DO SISPAG"),
  _60("60", "ENTRADA REJEITADA CARNÊ (NOTA 20 – TABELA 1)"),
  _61("61", "TARIFA EMISSÃO AVISO DE MOVIMENTAÇÃO DE TÍTULOS (2154)"),
  _62("62", "DÉBITO MENSAL DE TARIFA – AVISO DE MOVIMENTAÇÃO DE TÍTULOS (2154)"),
  _63("63", "TÍTULO SUSTADO JUDICIALMENTE"),
  _64("64", "ENTRADA CONFIRMADA COM RATEIO DE CRÉDITO"),
  _65("65", "PAGAMENTO COM CHEQUE – AGUARDANDO COMPENSAÇÃO"),
  _69("69", "CHEQUE DEVOLVIDO (NOTA 20 – TABELA 9)"),
  _71("71", "ENTRADA REGISTRADA, AGUARDANDO AVALIAÇÃO"),
  _72("72", "BAIXA POR CRÉDITO EM C/C ATRAVÉS DO SISPAG SEM TÍTULO CORRESPONDENTE"),
  _73("73", "CONFIRMAÇÃO DE ENTRADA NA COBRANÇA SIMPLES – ENTRADA NÃO ACEITA NA COBRANÇA CONTRATUAL"),
  _74("74", "INSTRUÇÃO DE NEGATIVAÇÃO EXPRESSA REJEITADA (NOTA 20 – TABELA 11)"),
  _75("75", "CONFIRMAÇÃO DE RECEBIMENTO DE INSTRUÇÃO DE ENTRADA EM NEGATIVAÇÃO EXPRESSA"),
  _76("76", "CHEQUE COMPENSADO"),
  _77("77", "CONFIRMAÇÃO DE RECEBIMENTO DE INSTRUÇÃO DE EXCLUSÃO DE ENTRADA EM NEGATIVAÇÃO EXPRESSA"),
  _78("78", "CONFIRMAÇÃO DE RECEBIMENTO DE INSTRUÇÃO DE CANCELAMENTO DE NEGATIVAÇÃO EXPRESSA"),
  _79("79", "NEGATIVAÇÃO EXPRESSA INFORMACIONAL (NOTA 20 – TABELA 12)"),
  _80("80", "CONFIRMAÇÃO DE ENTRADA EM NEGATIVAÇÃO EXPRESSA – TARIFA"),
  _82("82", "CONFIRMAÇÃO DO CANCELAMENTO DE NEGATIVAÇÃO EXPRESSA – TARIFA"),
  _83("83", "CONFIRMAÇÃO DE EXCLUSÃO DE ENTRADA EM NEGATIVAÇÃO EXPRESSA POR LIQUIDAÇÃO – TARIFA"),
  _85("85", "TARIFA POR BOLETO (ATÉ 03 ENVIOS) COBRANÇA ATIVA ELETRÔNICA"),
  _86("86", "TARIFA EMAIL COBRANÇA ATIVA ELETRÔNICA"),
  _87("87", "TARIFA SMS COBRANÇA ATIVA ELETRÔNICA"),
  _88("88", "TARIFA MENSAL POR BOLETO (ATÉ 03 ENVIOS) COBRANÇA ATIVA ELETRÔNICA"),
  _89("89", "TARIFA MENSAL EMAIL COBRANÇA ATIVA ELETRÔNICA"),
  _90("90", "TARIFA MENSAL SMS COBRANÇA ATIVA ELETRÔNICA"),
  _91("91", "TARIFA MENSAL DE EXCLUSÃO DE ENTRADA DE NEGATIVAÇÃO EXPRESSA"),
  _92("92", "TARIFA MENSAL DE CANCELAMENTO DE NEGATIVAÇÃO EXPRESSA"),
  _93("93", "TARIFA MENSAL DE EXCLUSÃO DE NEGATIVAÇÃO EXPRESSA POR LIQUIDAÇÃO"),
  _NA("NA", "Não listado");

  private String value;

  private String label;

  OcorrenciasRecebimentoEnum(String value, String label) {
    this.value = value;
    this.label = label;
  }

  public String getValue() {
    return value;
  }

  public String getLabel() {
    return label;
  }

  public static OcorrenciasRecebimentoEnum byValue(String value) {
    for (OcorrenciasRecebimentoEnum _enum : OcorrenciasRecebimentoEnum.values()) {
      if (_enum.value.equals(value)) {
        return _enum;
      }
    }
    return _NA;
  }
}
